### PR TITLE
Update readme to work with newest Docker library

### LINKED ISSUE #78: dockerpty not compatible with docker 2.4.2
Please correct me if I'm wrong, but it's my understanding that [docker-py](https://pypi.python.org/pypi/docker-py) is superseded by [docker](https://pypi.python.org/pypi/docker) as the "official" Python Docker API binding. If so, dockerpty does not work with docker 2.4.2 and gives the following stacktrace:

```python
Traceback (most recent call last):
  File "./build.py", line 104, in <module>
    dockerpty.start(docker_client, container)
  File ".../site-packages/dockerpty/__init__.py", line 30, in start
    PseudoTerminal(client, operation).start()
  File ".../site-packages/dockerpty/pty.py", line 328, in start
    pumps = self.operation.start(sockets=sockets)
  File ".../site-packages/dockerpty/pty.py", line 136, in start
    pty_stdin, pty_stdout, pty_stderr = sockets or self.sockets()
  File ".../site-packages/dockerpty/pty.py", line 174, in sockets
    info = self._container_info()
  File ".../site-packages/dockerpty/pty.py", line 204, in _container_info
    return self.client.inspect_container(self.container)
  File ".../site-packages/docker/client.py", line 187, in __getattr__
    raise AttributeError(' '.join(s))
AttributeError: 'DockerClient' object has no attribute 'inspect_container' In Docker SDK for Python 2.0, this method is now on the object APIClient. See the low-level API section of the documentation for more details.
```

### LINKED ISSUE #79: Dockerpty not compatible with docker version 3.0.0
Looks like dockerpty is not compatible with docker version 3.0.0.

### PR DESCRIPTION
**Pull request by tedivm**
When docker ditched the `docker-py` library in favor of `docker` on PyPI they made a few very very small changes that break this library.

I've gone ahead and upgraded the readme to work with these new changes. I should point out that these changes are trivial- it basically amounts to changing `docker.client()` to `docker.APIClient()`. That's because the "low level API" that this project is based on has moved- but it is still there, and completely compatible with this library. Literally all anyone has to do in order to use the latest docker python library is change that one call so they get the low level client instead of the high level one.

resolves #78 
resolves #79

### CODE REVIEW

**Review by aureliojargas — APPROVED** [review]
I confirm that this worked for me using the latest `dockerpty` and `docker` SDK 4.1.0.

**Comment by acerv** [comment]
Hello, Is there a plan to update the documentation?
At the moment, this is the only working library to get docker tty :)

Thanks for your work,
Andrea
